language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - make requirements-test
  - pip install coveralls
# command to run tests
script:
  - make prepush
after_success:
  - coveralls --rcfile=.coveragerc
cache: pip
sudo: false