language: python
python:
  - "3.3"
# command to install dependencies
install: "pip install -r requirements-test.txt"
# command to run tests
script:
    - flake8 .
    - nosetests --with-coverage -d --cover-package=dirty_validators  
after_success:
  - coveralls --rcfile=.coveragerc
